pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-2"
        ACCOUNT_ID = "652942059461"
        ECR_REPO_NAME = "webapp"
        ECR_REPO_URI = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}"
        CLUSTER_NAME = "webapp-cluster"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/G1RAAJ/Devops-projects.git'
            }
        }

        stage('Debug') {
            steps {
                sh '''
                whoami
                pwd
                aws sts get-caller-identity
                ls
                ls webapp-project
                ls webapp-project/terraform
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('webapp-project/terraform') {
                    sh '''
                    terraform init -upgrade
                    terraform validate
                    terraform apply -auto-approve -var-file=terraform.tfvars
                    '''
                }
            }
        }

        stage('Configure EKS Access') {
            steps {
                sh '''
                aws eks create-access-entry \
                --cluster-name $CLUSTER_NAME \
                --principal-arn arn:aws:iam::$ACCOUNT_ID:role/webapp-role \
                --region $AWS_REGION || true
        
                aws eks associate-access-policy \
                --cluster-name $CLUSTER_NAME \
                --principal-arn arn:aws:iam::$ACCOUNT_ID:role/webapp-role \
                --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy \
                --access-scope type=cluster \
                --region $AWS_REGION || true
                '''
            }
        }

        stage('Create ECR Repo') {
            steps {
                sh '''
                aws ecr describe-repositories \
                --repository-names $ECR_REPO_NAME \
                --region $AWS_REGION || \
                aws ecr create-repository \
                --repository-name $ECR_REPO_NAME \
                --region $AWS_REGION
                '''
            }
        }

        stage('Build Docker') {
            steps {
                sh 'cd webapp-project/app && docker build -t webapp .'
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password \
                --region $AWS_REGION | \
                docker login \
                --username AWS \
                --password-stdin \
                $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Push to ECR') {
            steps {
                sh '''
                docker tag webapp:latest $ECR_REPO_URI:$BUILD_NUMBER
                docker push $ECR_REPO_URI:$BUILD_NUMBER
                '''
            }
        }

        stage('Update kubeconfig') {
            steps {
                sh '''
                mkdir -p ~/.kube
                rm -f ~/.kube/config
                aws eks update-kubeconfig \
                --region $AWS_REGION \
                --name $CLUSTER_NAME
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                helm upgrade --install webapp ./webapp-project/helm/webapp \
                --set image.repository=$ECR_REPO_URI \
                --set image.tag=$BUILD_NUMBER
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                sh '''
                kubectl get nodes
                kubectl get pods
                kubectl get svc
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful'
        }

        failure {
            echo 'Pipeline Failed'
        }
    }
}
