pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-2"
        ACCOUNT_ID = "652942059461"
        ECR_REPO_NAME = "sockshop"
        ECR_REPO_URI = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}"
        CLUSTER_NAME = "sockshop-cluster"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/G1RAAJ/Devops-projects.git'
            }
        }   
        
        // -------------Terraform------------------
        stage('Terraform Apply') {
            steps {
                dir('sockshop/terraform') {
                    sh '''
                    terraform init
                    terraform apply -auto-approve -var-file=terraform.tfvars
                    '''
                }
            }
        }

        // ------------Ensure ECR Repo--------------
        stage('Create ECR Repo') {
            steps {
                sh '''
                aws ecr create-repository \
                --repository-name $ECR_REPO_NAME \
                --region $AWS_REGION
                '''
            }
        }
      
        // -------------Build Docker Image----------
        stage('Build Docker') {
            steps {
                sh '''
                docker build -t sockshop ./sockshop/docker/frontend
                '''
            }
        }
        
        // ------------ Login to ECR---------------
        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS \
                --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }
   
        // ------------Push Image to ECR-----------
        stage('Push to ECR') {
            steps {
                sh '''
                docker tag frontend:latest $ECR_REPO_URI:latest
                docker push $ECR_REPO_URI:latest
                '''
            }
        }
        
        // ------------Configure kubectl-----------
        stage('Update kubeconfig') {
            steps {
                sh '''
                aws eks update-kubeconfig \
                --region $AWS_REGION \
                --name $CLUSTER_NAME
                '''
            }
        }
 
        // -------Deploy to EKS using Helm---------
        stage('Deploy') {
            steps {
                sh '''
                helm upgrade --install sockshop ./sockshop/helm/sockshop \
                --set image.repository=$ECR_REPO_URL \
                --set image.tag=latest
                '''
            }
        }
    }
}
